/*
 * eps_com.h
 * 
 * Copyright (C) 2017, Federal University of Santa Catarina
 * 
 * This file is part of FloripaSat-Beacon.
 * 
 * FloripaSat-Beacon is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * FloripaSat-Beacon is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with FloripaSat-Beacon. If not, see <http://www.gnu.org/licenses/>.
 * 
 */

/**
 * \file eps_com.h
 * 
 * \brief Functions to receive data from EPS module
 * 
 * \author Gabriel Mariano Marcelino <gabriel.mm8@gmail.com>
 * 
 * \version 1.0-dev
 * 
 * \date 23/09/2016
 * 
 * \defgroup eps_com EPS Communication
 * \ingroup modules
 * \{
 */

#ifndef EPS_COM_H_
#define EPS_COM_H_

#include <stdint.h>
#include <libs/driverlib/driverlib.h>
#include <config/config.h>

#define EPS_COM_PKT_LEN                     0x04
#define EPS_COM_PKT_SOD                     0x7E
#define EPS_COM_PKT_BYTE_COUNTER_POS_SOD    0x00
#define EPS_COM_PKT_BYTE_COUNTER_POS_CRC    (EPS_COM_PKT_LEN+1)

#define EPS_COM_DEFAULT_DATA_MSB            0x07
#define EPS_COM_DEFAULT_DATA_LSB            0xFD
#define EPS_COM_CRC_INITIAL_VALUE           0x00
#define EPS_COM_CRC_POLY                    0x07

/**
 * \struct EPS_Com
 * 
 * \brief EPS communication variables struct.
 */
typedef struct
{
    uint8_t received_byte;                  /**< Byte buffer. */
    uint8_t byte_counter;                   /**< Received packet byte counter. */
    uint8_t buffer[EPS_COM_PKT_LEN + 1];    /**< Packet buffer. */
} EPSCom;

/**
 * \struct EPSData
 * 
 * \brief Struct to store the data from the EPS module.
 */
typedef struct
{
    uint8_t bat1_msb;
    uint8_t bat1_lsb;
    uint8_t bat2_msb;
    uint8_t bat2_lsb;
} EPSData;

/**
 * \var eps_com
 * 
 * \brief 
 */
extern EPSCom eps_com;

/**
 * \var eps_data
 * 
 * \brief EPS data object.
 */
extern EPSData eps_data;

/**
 * \fn eps_com_init
 * 
 * \brief Initialization of the EPS communication module.
 * 
 * \return Initialization status. It can be:
 *      - \b STATUS_SUCCESS
 *      - \b STATUS_FAIL
 *      .
 */
uint8_t eps_com_init();

/**
 * \fn eps_com_receive_data
 * 
 * \brief Receives the data coming from the EPS module.
 * 
 * This is function only must be called from an interruption generated by
 * the EPS module.
 * 
 * \return None
 */
static void eps_com_receive_data();

#endif // EPS_COM_H_

//! \} End of eps_com group
